name:                parser-example
version:             0.1.0.0
github:              "piotrMocz/parser-example"
license:             BSD3
author:              "Piotr Moczurad"
maintainer:          "piotr.moczurad@luna-lang.org"
copyright:           "2018 Piotr Moczurad"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- text
- megaparsec == 7.0.1

library:
  source-dirs: src

executables:
  parser-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parser-example

tests:
  parser-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parser-example
    - hspec
    - QuickCheck
